server:
  port: 8189
  servlet:
    context-path: /winter

jwt:
  secret: fg4564hgdhK4564GHHGfgd54lljHJKda456s4
  lifetime: 36000000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: admin
    password:
  jpa:
    show-sql: true
    propertyes:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
#      path: /winter/h2-console
      settings:
#        trace: true
        web-allow-others: false


