server:
  port: 8189
  servlet:
    context-path: /winter-market-core
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
integrations:
  cart-service:
    url: http://localhost:8190/winter-market-carts/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000



#server:
#  port: 8189
#  servlet:
#    context-path: /winter-market-core
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://postgres:5432/postgres
#    username: postgres
#    password: postgres
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#integrations:
#  cart-service:
#    url: http://redis:6379
#    connect-timeout: 5000
#    read-timeout: 10000
#    write-timeout: 5000
